name: Test change-aws-credentials
on:
  #  # Uncomment when test added first time to register workflow and comment it back after workflow would be registered
  #  #
  #  # Added pull_request to register workflow from the PR.
  #  # Read more https://stackoverflow.com/questions/63362126/github-actions-how-to-run-a-workflow-created-on-a-non-master-branch-from-the-wo
  # pull_request: {}
  workflow_dispatch: {}

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Setup
        run: echo "Do setup"

  test:
    needs: [setup]
    strategy:
      matrix:
        runs-on: ["ubuntu-latest", "macos-latest"]
    runs-on: ${{ matrix.runs-on }}
    steps:
      - uses: actions/checkout@v1
      - run: npm ci
      - run: npm run build
      - uses: ./
        with:
          repo: jaxxstorm/change-aws-credentials
          tag: v0.4.0
      - run: change-aws-credentials version

  assert:
    runs-on: ubuntu-latest
    needs: [test]
    steps:
      - uses: nick-fields/assert-action@v1
        with:
          expected: 'success'
          actual: ${{ needs.test.result }}
