name: Test prometheus
on:
  #  # Uncomment when test added first time to register workflow and comment it back after workflow would be registered
  #  #
  #  # Added pull_request to register workflow from the PR.
  #  # Read more https://stackoverflow.com/questions/63362126/github-actions-how-to-run-a-workflow-created-on-a-non-master-branch-from-the-wo
  # pull_request: {}
  workflow_dispatch: {}

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Setup
        run: echo "Do setup"

  test:
    needs: [setup]
    strategy:
      matrix:
        version: [ "latest" ]
        runs-on: [ "ubuntu-latest" ]
        arch: [ "amd64" ]
        include:
          - runs-on: "ubuntu-latest"
            platform: linux
    runs-on: ${{ matrix.runs-on }}
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: 'npm'
      - run: npm ci
      - run: npm run build
      - uses: ./
        with:
          repo: prometheus/prometheus
          tag: 'v2.37.9'
          platform: linux
          arch: amd64
          cache: enable
          binaries-location: prometheus-2.37.9.linux-amd64
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: promtool --version

  assert:
    runs-on: ubuntu-latest
    needs: [test]
    steps:
      - uses: nick-fields/assert-action@v1
        with:
          expected: 'success'
          actual: ${{ needs.test.result }}
